# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIOcelotInterface.ui'
#
# Created: Wed Mar  8 12:33:07 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1050, 825)
        Form.setMinimumSize(QtCore.QSize(400, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setStyleSheet(_fromUtf8("background-color: white"))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startButton = QtGui.QPushButton(self.tab)
        self.startButton.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_2.addWidget(self.startButton)
        self.logButton = QtGui.QPushButton(self.tab)
        self.logButton.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logButton.setFont(font)
        self.logButton.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.logButton.setObjectName(_fromUtf8("logButton"))
        self.horizontalLayout_2.addWidget(self.logButton)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.helpButton = QtGui.QPushButton(self.frame)
        self.helpButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.helpButton.setFont(font)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.gridLayout_2.addWidget(self.helpButton, 2, 0, 1, 1)
        self.heatmapButton = QtGui.QPushButton(self.frame)
        self.heatmapButton.setMinimumSize(QtCore.QSize(0, 20))
        self.heatmapButton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.heatmapButton.setFont(font)
        self.heatmapButton.setObjectName(_fromUtf8("heatmapButton"))
        self.gridLayout_2.addWidget(self.heatmapButton, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.widget = ResetpanelBoxWindow(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(550, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_9.addWidget(self.widget, 0, 0, 2, 1)
        self.widget_2 = QtGui.QWidget(self.tab)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_9.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_9.addWidget(self.widget_3, 1, 1, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.addDevice = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addDevice.setFont(font)
        self.addDevice.setStyleSheet(_fromUtf8("color:orange"))
        self.addDevice.setObjectName(_fromUtf8("addDevice"))
        self.gridLayout_8.addWidget(self.addDevice, 1, 1, 1, 1)
        self.deviceList = QtGui.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deviceList.setFont(font)
        self.deviceList.setStyleSheet(_fromUtf8("color:white"))
        self.deviceList.setObjectName(_fromUtf8("deviceList"))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.deviceList.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.deviceList, 1, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 2, 4, 1, 1)
        self.remDevice = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.remDevice.setFont(font)
        self.remDevice.setStyleSheet(_fromUtf8("color:white"))
        self.remDevice.setObjectName(_fromUtf8("remDevice"))
        self.gridLayout_8.addWidget(self.remDevice, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 1, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 2, 3, 1, 1)
        self.deviceEnter = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deviceEnter.setFont(font)
        self.deviceEnter.setObjectName(_fromUtf8("deviceEnter"))
        self.gridLayout_8.addWidget(self.deviceEnter, 2, 5, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 2, 2, 1, 1)
        self.rate_label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.rate_label.setFont(font)
        self.rate_label.setStyleSheet(_fromUtf8("color:green"))
        self.rate_label.setText(_fromUtf8(""))
        self.rate_label.setObjectName(_fromUtf8("rate_label"))
        self.gridLayout_8.addWidget(self.rate_label, 0, 5, 1, 1)
        self.messages = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.messages.setFont(font)
        self.messages.setText(_fromUtf8(""))
        self.messages.setObjectName(_fromUtf8("messages"))
        self.gridLayout_8.addWidget(self.messages, 4, 5, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_3 = QtGui.QLabel(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setMargin(5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_12.addWidget(self.label_3)
        self.groupBox_3 = QtGui.QGroupBox(self.tab2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setEnabled(True)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.obj_func_edit = QtGui.QLineEdit(self.groupBox_3)
        self.obj_func_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.obj_func_edit.setFont(font)
        self.obj_func_edit.setObjectName(_fromUtf8("obj_func_edit"))
        self.verticalLayout_5.addWidget(self.obj_func_edit)
        self.select_optimizer = QtGui.QComboBox(self.groupBox_3)
        self.select_optimizer.setEnabled(True)
        self.select_optimizer.setMinimumSize(QtCore.QSize(0, 0))
        self.select_optimizer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.select_optimizer.setFont(font)
        self.select_optimizer.setObjectName(_fromUtf8("select_optimizer"))
        self.verticalLayout_5.addWidget(self.select_optimizer)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.tab2)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.trim_delay_edit = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.trim_delay_edit.setFont(font)
        self.trim_delay_edit.setObjectName(_fromUtf8("trim_delay_edit"))
        self.verticalLayout_7.addWidget(self.trim_delay_edit)
        self.data_points_edit = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.data_points_edit.setFont(font)
        self.data_points_edit.setObjectName(_fromUtf8("data_points_edit"))
        self.verticalLayout_7.addWidget(self.data_points_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.delay_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.delay_label.setFont(font)
        self.delay_label.setText(_fromUtf8(""))
        self.delay_label.setObjectName(_fromUtf8("delay_label"))
        self.gridLayout_5.addWidget(self.delay_label, 2, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.tab2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setEnabled(True)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.norm_scale_edit = QtGui.QLineEdit(self.groupBox_4)
        self.norm_scale_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.norm_scale_edit.setFont(font)
        self.norm_scale_edit.setObjectName(_fromUtf8("norm_scale_edit"))
        self.verticalLayout_9.addWidget(self.norm_scale_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.normscale_check = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.normscale_check.setFont(font)
        self.normscale_check.setObjectName(_fromUtf8("normscale_check"))
        self.gridLayout_6.addWidget(self.normscale_check, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.tab2)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.hyps_edit = QtGui.QLineEdit(self.groupBox_2)
        self.hyps_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hyps_edit.setFont(font)
        self.hyps_edit.setObjectName(_fromUtf8("hyps_edit"))
        self.verticalLayout_2.addWidget(self.hyps_edit)
        self.seed_file_edit = QtGui.QLineEdit(self.groupBox_2)
        self.seed_file_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.seed_file_edit.setFont(font)
        self.seed_file_edit.setObjectName(_fromUtf8("seed_file_edit"))
        self.verticalLayout_2.addWidget(self.seed_file_edit)
        self.hyp_scale_edit = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hyp_scale_edit.setFont(font)
        self.hyp_scale_edit.setObjectName(_fromUtf8("hyp_scale_edit"))
        self.verticalLayout_2.addWidget(self.hyp_scale_edit)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.live_seed_check = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.live_seed_check.setFont(font)
        self.live_seed_check.setObjectName(_fromUtf8("live_seed_check"))
        self.gridLayout_3.addWidget(self.live_seed_check, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.devButton = QtGui.QPushButton(self.tab2)
        self.devButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.devButton.setFont(font)
        self.devButton.setObjectName(_fromUtf8("devButton"))
        self.verticalLayout_12.addWidget(self.devButton)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Ocelot Interface", None))
        self.startButton.setText(_translate("Form", "Start Scan", None))
        self.logButton.setText(_translate("Form", "Logbook", None))
        self.helpButton.setText(_translate("Form", "Help/Docs", None))
        self.heatmapButton.setText(_translate("Form", "GP 2D Heatmap", None))
        self.addDevice.setText(_translate("Form", "Add Devices", None))
        self.deviceList.setItemText(0, _translate("Form", "IN20 M. Quads", None))
        self.deviceList.setItemText(1, _translate("Form", "LI21 M. Quads", None))
        self.deviceList.setItemText(2, _translate("Form", "LI26 201-501", None))
        self.deviceList.setItemText(3, _translate("Form", "LI26 601-901", None))
        self.deviceList.setItemText(4, _translate("Form", "LTU M. Quads", None))
        self.deviceList.setItemText(5, _translate("Form", "Dispersion Quads", None))
        self.deviceList.setItemText(6, _translate("Form", "CQ01/SQ01/Sol.", None))
        self.deviceList.setItemText(7, _translate("Form", "DMD PVs", None))
        self.label_13.setText(_translate("Form", "Or Manually Enter", None))
        self.remDevice.setText(_translate("Form", "Clear Devices", None))
        self.label_12.setText(_translate("Form", "From List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Optimization Scan Panel", None))
        self.label_3.setText(_translate("Form", "Scanner Setup and Options Panel", None))
        self.groupBox_3.setTitle(_translate("Form", "General Config", None))
        self.label.setText(_translate("Form", "Objective Function PV  ", None))
        self.label_5.setText(_translate("Form", "Select Optimiser Algorithm", None))
        self.groupBox.setTitle(_translate("Form", "Scanner Timing", None))
        self.label_2.setText(_translate("Form", "Trim Delay (seconds)  ", None))
        self.label_6.setText(_translate("Form", "Data Points", None))
        self.groupBox_4.setTitle(_translate("Form", "Simplex/Scipy Scanner Setup", None))
        self.label_11.setText(_translate("Form", "Normalization Scaling Coeff", None))
        self.normscale_check.setText(_translate("Form", "Use Normalization Scaling", None))
        self.groupBox_2.setTitle(_translate("Form", "GP Scanner Setup", None))
        self.label_9.setText(_translate("Form", "GP Hyperparameter FIle", None))
        self.label_8.setText(_translate("Form", "GP Seed File", None))
        self.label_7.setText(_translate("Form", "Hyperparameter Scaling", None))
        self.live_seed_check.setText(_translate("Form", "Use Live Simplex Seed Mode", None))
        self.devButton.setText(_translate("Form", "Dev Ocelot Epics Panel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "Scan Setup Panel", None))

from resetpanel.resetpanelbox import ResetpanelBoxWindow
